"""sync comments notas_fiscais decisao_75

Revision ID: 266a68ac8352
Revises: c7f2c186e167
Create Date: 2026-07-28 20:40:09.533047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '266a68ac8352'
down_revision: Union[str, None] = 'c7f2c186e167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas_fiscais', 'embarque_id',
               existing_type=sa.UUID(),
               comment='Embarque ao qual esta NF pertence. Portador do tenant (embarques.empresa_id).',
               existing_comment='Embarque ao qual esta NF pertence',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha (Seção 4.1).',
               existing_comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cod_remetente',
               existing_type=sa.VARCHAR(length=50),
               comment='Código do remetente. Origem: coluna COD REMETENTE (Seção 4.1).',
               existing_comment='Código do remetente. Origem: coluna COD REMETENTE.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cliente_remetente',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social do remetente. Origem: coluna CLIENTE REMETENTE (Seção 4.1).',
               existing_comment='Nome do remetente. Origem: coluna CLIENTE REMETENTE.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cnpj_remetente',
               existing_type=sa.VARCHAR(length=14),
               comment='CNPJ do remetente, somente dígitos (14). Origem: coluna CNPJ REMETENTE (Seção 4.1).',
               existing_comment='CNPJ do emitente (14 dígitos, sem máscara). Origem: coluna CNPJ REMETENTE.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_remetente',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade de origem, derivada de cidade_remetente_raw. Chave de rota no cálculo (Seção 5.4 / 6.2).',
               existing_comment='Cidade de origem. Derivado de CIDADE - UF REMETENTE (Seção 4.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'uf_remetente',
               existing_type=sa.VARCHAR(length=2),
               comment='UF de origem (2 letras), derivada de cidade_remetente_raw. Chave de rota (Seção 5.4).',
               existing_comment='UF de origem (2 letras). Derivado de CIDADE - UF REMETENTE (Seção 4.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_remetente_raw',
               existing_type=sa.VARCHAR(length=200),
               comment="Valor original da coluna 'CIDADE - UF REMETENTE', preservado como veio na planilha (Seção 4.2).",
               existing_comment='Valor original de CIDADE - UF REMETENTE antes da normalização (Seção 4.2).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'cod_cliente',
               existing_type=sa.VARCHAR(length=50),
               comment='Código do cliente destino. Origem: coluna COD CLIENTE (Seção 4.1).',
               existing_comment='Código do cliente destino. Origem: coluna COD CLIENTE.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cliente_destino',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social do destinatário. Origem: coluna CLIENTE DESTINO (Seção 4.1).',
               existing_comment='Nome do cliente destino. Origem: coluna CLIENTE DESTINO.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cnpj_destino',
               existing_type=sa.VARCHAR(length=14),
               comment='CNPJ do destinatário, somente dígitos (14). Origem: coluna CNPJ DESTINO (Seção 4.1).',
               existing_comment='CNPJ do destinatário (14 dígitos, sem máscara). Origem: coluna CNPJ DESTINO.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_destino',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade de destino, derivada de cidade_destino_raw. Chave de rota no cálculo (Seção 5.4 / 6.2).',
               existing_comment='Cidade de destino. Derivado de CIDADE - UF DESTINO (Seção 4.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'uf_destino',
               existing_type=sa.VARCHAR(length=2),
               comment='UF de destino (2 letras), derivada de cidade_destino_raw. Chave de rota (Seção 5.4).',
               existing_comment='UF de destino (2 letras). Ex: SP, RJ, MG. Derivado de CIDADE - UF DESTINO (Seção 4.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_destino_raw',
               existing_type=sa.VARCHAR(length=200),
               comment="Valor original da coluna 'CIDADE - UF DESTINO', preservado como veio na planilha (Seção 4.2).",
               existing_comment='Valor original de CIDADE - UF DESTINO antes da normalização (Seção 4.2).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'peso_total_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso total da NF em kg. Fórmula: qtd_cx × produto.peso_real_kg (Seção 3.1 / 4.3). Armazenado para auditoria e reprocessabilidade.',
               existing_comment='Peso total da NF em kg. Fórmula: QTD_CX × produto.peso_real_kg (Seção 3.1). Armazenado para auditoria e reprocessabilidade.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('pendente', 'calculado', 'erro', 'ignorada', 'sem_tabela', 'sem_transportadora', name='statuscalculonf'),
               comment="Status do cálculo de frete (Seção 6.7). Nasce como 'pendente' após importação válida.",
               existing_comment='Status do cálculo de frete (Seção 6.7).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Campo livre, sem validação. Origem: coluna OBSERVAÇÃO (Seção 4.1).',
               existing_comment='Campo livre. Origem: coluna OBSERVAÇÃO.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'centro_custo',
               existing_type=sa.TEXT(),
               comment='Campo livre, sem validação. Origem: coluna CENTRO DE CUSTO (Seção 4.1).',
               existing_comment='Campo livre. Origem: coluna CENTRO DE CUSTO.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas_fiscais', 'centro_custo',
               existing_type=sa.TEXT(),
               comment='Campo livre. Origem: coluna CENTRO DE CUSTO.',
               existing_comment='Campo livre, sem validação. Origem: coluna CENTRO DE CUSTO (Seção 4.1).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Campo livre. Origem: coluna OBSERVAÇÃO.',
               existing_comment='Campo livre, sem validação. Origem: coluna OBSERVAÇÃO (Seção 4.1).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('pendente', 'calculado', 'erro', 'ignorada', 'sem_tabela', 'sem_transportadora', name='statuscalculonf'),
               comment='Status do cálculo de frete (Seção 6.7).',
               existing_comment="Status do cálculo de frete (Seção 6.7). Nasce como 'pendente' após importação válida.",
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'peso_total_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso total da NF em kg. Fórmula: QTD_CX × produto.peso_real_kg (Seção 3.1). Armazenado para auditoria e reprocessabilidade.',
               existing_comment='Peso total da NF em kg. Fórmula: qtd_cx × produto.peso_real_kg (Seção 3.1 / 4.3). Armazenado para auditoria e reprocessabilidade.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_destino_raw',
               existing_type=sa.VARCHAR(length=200),
               comment='Valor original de CIDADE - UF DESTINO antes da normalização (Seção 4.2).',
               existing_comment="Valor original da coluna 'CIDADE - UF DESTINO', preservado como veio na planilha (Seção 4.2).",
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'uf_destino',
               existing_type=sa.VARCHAR(length=2),
               comment='UF de destino (2 letras). Ex: SP, RJ, MG. Derivado de CIDADE - UF DESTINO (Seção 4.2).',
               existing_comment='UF de destino (2 letras), derivada de cidade_destino_raw. Chave de rota (Seção 5.4).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_destino',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade de destino. Derivado de CIDADE - UF DESTINO (Seção 4.2).',
               existing_comment='Cidade de destino, derivada de cidade_destino_raw. Chave de rota no cálculo (Seção 5.4 / 6.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cnpj_destino',
               existing_type=sa.VARCHAR(length=14),
               comment='CNPJ do destinatário (14 dígitos, sem máscara). Origem: coluna CNPJ DESTINO.',
               existing_comment='CNPJ do destinatário, somente dígitos (14). Origem: coluna CNPJ DESTINO (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cliente_destino',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do cliente destino. Origem: coluna CLIENTE DESTINO.',
               existing_comment='Razão social do destinatário. Origem: coluna CLIENTE DESTINO (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cod_cliente',
               existing_type=sa.VARCHAR(length=50),
               comment='Código do cliente destino. Origem: coluna COD CLIENTE.',
               existing_comment='Código do cliente destino. Origem: coluna COD CLIENTE (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_remetente_raw',
               existing_type=sa.VARCHAR(length=200),
               comment='Valor original de CIDADE - UF REMETENTE antes da normalização (Seção 4.2).',
               existing_comment="Valor original da coluna 'CIDADE - UF REMETENTE', preservado como veio na planilha (Seção 4.2).",
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'uf_remetente',
               existing_type=sa.VARCHAR(length=2),
               comment='UF de origem (2 letras). Derivado de CIDADE - UF REMETENTE (Seção 4.2).',
               existing_comment='UF de origem (2 letras), derivada de cidade_remetente_raw. Chave de rota (Seção 5.4).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cidade_remetente',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade de origem. Derivado de CIDADE - UF REMETENTE (Seção 4.2).',
               existing_comment='Cidade de origem, derivada de cidade_remetente_raw. Chave de rota no cálculo (Seção 5.4 / 6.2).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cnpj_remetente',
               existing_type=sa.VARCHAR(length=14),
               comment='CNPJ do emitente (14 dígitos, sem máscara). Origem: coluna CNPJ REMETENTE.',
               existing_comment='CNPJ do remetente, somente dígitos (14). Origem: coluna CNPJ REMETENTE (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cliente_remetente',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome do remetente. Origem: coluna CLIENTE REMETENTE.',
               existing_comment='Razão social do remetente. Origem: coluna CLIENTE REMETENTE (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'cod_remetente',
               existing_type=sa.VARCHAR(length=50),
               comment='Código do remetente. Origem: coluna COD REMETENTE.',
               existing_comment='Código do remetente. Origem: coluna COD REMETENTE (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha.',
               existing_comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha (Seção 4.1).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'embarque_id',
               existing_type=sa.UUID(),
               comment='Embarque ao qual esta NF pertence',
               existing_comment='Embarque ao qual esta NF pertence. Portador do tenant (embarques.empresa_id).',
               existing_nullable=False)
    # ### end Alembic commands ###
