"""cria_produto_sem_cubagem

Revision ID: 525c87ab03c2
Revises: 73cb07162d9a
Create Date: 2026-07-06 20:31:10.596033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525c87ab03c2'
down_revision: Union[str, None] = '73cb07162d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
