"""remove_frete_gris_advalorem_despacho

Revision ID: 73cb07162d9a
Revises: f27d4de3245e
Create Date: 2026-07-06 20:06:40.886762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73cb07162d9a'
down_revision: Union[str, None] = 'f27d4de3245e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Numero da nota fiscal. Unico dentro do embarque.',
               existing_comment='Número da nota fiscal. Único dentro do embarque.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'serie_nf',
               existing_type=sa.VARCHAR(length=10),
               comment='Serie da nota fiscal. Ex: 001, A, B.',
               existing_comment='Série da nota fiscal. Ex: 001, A, B.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'chave_nfe',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso da NF-e (44 digitos). Opcional — usado na auditoria com CT-e.',
               existing_comment='Chave de acesso da NF-e (44 dígitos). Opcional — usado na auditoria com CT-e.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'data_emissao',
               existing_type=sa.DATE(),
               comment='Data de emissao da nota fiscal',
               existing_comment='Data de emissão da nota fiscal',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Razao social ou nome do destinatario',
               existing_comment='Razão social ou nome do destinatário',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_cnpj_cpf',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ ou CPF do destinatario. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX',
               existing_comment='CNPJ ou CPF do destinatário. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_cidade',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade do destinatario',
               existing_comment='Cidade do destinatário',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_uf',
               existing_type=sa.VARCHAR(length=2),
               comment='UF do destinatario. Ex: SP, RJ, MG.',
               existing_comment='UF do destinatário. Ex: SP, RJ, MG.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'nf_valor',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor total da nota fiscal em R$.',
               existing_comment='Valor total da nota fiscal em R$. Base para cálculo de GRIS e Ad Valorem.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'peso_real_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. E a metrica unica de peso para calculo de frete — o projeto NAO utiliza cubagem.',
               existing_comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. É a métrica única de peso para cálculo de frete — o projeto NÃO utiliza cubagem.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'frete_cte',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Taxa de emissao de CT-e em R$, conforme tabela de frete.',
               existing_comment='Taxa de emissão de CT-e em R$, conforme tabela de frete.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'frete_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Frete total da NF em R$. = frete_peso + frete_cte',
               existing_comment='Frete total da NF em R$. = frete_peso + frete_gris + frete_advalorem + frete_despacho + frete_cte',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('PENDENTE', 'CALCULADO', 'ERRO', 'IGNORADA', name='statuscalculonf'),
               comment='Status atual do calculo de frete desta NF',
               existing_comment='Status atual do cálculo de frete desta NF',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'erro_calculo',
               existing_type=sa.TEXT(),
               comment='Descricao do erro caso status_calculo = ERRO. Usado para revisao operacional.',
               existing_comment='Descrição do erro caso status_calculo = ERRO. Usado para revisão operacional.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observacoes livres sobre a NF',
               existing_comment='Observações livres sobre a NF',
               existing_nullable=True)
    op.drop_column('notas_fiscais', 'frete_advalorem')
    op.drop_column('notas_fiscais', 'frete_despacho')
    op.drop_column('notas_fiscais', 'frete_gris')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_fiscais', sa.Column('frete_gris', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Valor do GRIS calculado em R$. = max(nf_valor × percentual_gris, valor_minimo_gris)'))
    op.add_column('notas_fiscais', sa.Column('frete_despacho', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Taxa de despacho fixa em R$, conforme tabela de frete.'))
    op.add_column('notas_fiscais', sa.Column('frete_advalorem', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Valor do Ad Valorem calculado em R$. = nf_valor × percentual_advalorem'))
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observações livres sobre a NF',
               existing_comment='Observacoes livres sobre a NF',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'erro_calculo',
               existing_type=sa.TEXT(),
               comment='Descrição do erro caso status_calculo = ERRO. Usado para revisão operacional.',
               existing_comment='Descricao do erro caso status_calculo = ERRO. Usado para revisao operacional.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('PENDENTE', 'CALCULADO', 'ERRO', 'IGNORADA', name='statuscalculonf'),
               comment='Status atual do cálculo de frete desta NF',
               existing_comment='Status atual do calculo de frete desta NF',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'frete_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Frete total da NF em R$. = frete_peso + frete_gris + frete_advalorem + frete_despacho + frete_cte',
               existing_comment='Frete total da NF em R$. = frete_peso + frete_cte',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'frete_cte',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Taxa de emissão de CT-e em R$, conforme tabela de frete.',
               existing_comment='Taxa de emissao de CT-e em R$, conforme tabela de frete.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'peso_real_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. É a métrica única de peso para cálculo de frete — o projeto NÃO utiliza cubagem.',
               existing_comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. E a metrica unica de peso para calculo de frete — o projeto NAO utiliza cubagem.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'nf_valor',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor total da nota fiscal em R$. Base para cálculo de GRIS e Ad Valorem.',
               existing_comment='Valor total da nota fiscal em R$.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'destinatario_uf',
               existing_type=sa.VARCHAR(length=2),
               comment='UF do destinatário. Ex: SP, RJ, MG.',
               existing_comment='UF do destinatario. Ex: SP, RJ, MG.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_cidade',
               existing_type=sa.VARCHAR(length=100),
               comment='Cidade do destinatário',
               existing_comment='Cidade do destinatario',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_cnpj_cpf',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ ou CPF do destinatário. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX',
               existing_comment='CNPJ ou CPF do destinatario. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'destinatario_nome',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social ou nome do destinatário',
               existing_comment='Razao social ou nome do destinatario',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'data_emissao',
               existing_type=sa.DATE(),
               comment='Data de emissão da nota fiscal',
               existing_comment='Data de emissao da nota fiscal',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'chave_nfe',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso da NF-e (44 dígitos). Opcional — usado na auditoria com CT-e.',
               existing_comment='Chave de acesso da NF-e (44 digitos). Opcional — usado na auditoria com CT-e.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'serie_nf',
               existing_type=sa.VARCHAR(length=10),
               comment='Série da nota fiscal. Ex: 001, A, B.',
               existing_comment='Serie da nota fiscal. Ex: 001, A, B.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Número da nota fiscal. Único dentro do embarque.',
               existing_comment='Numero da nota fiscal. Unico dentro do embarque.',
               existing_nullable=False)
    # ### end Alembic commands ###
