"""remove cliente model; simplifica Cte (drop cancelado, total_calculado_nfs, divergencia_total)

Revision ID: c7f2c186e167
Revises: eec6940b1127
Create Date: 2026-07-11 14:02:12.701977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f2c186e167'
down_revision: Union[str, None] = 'eec6940b1127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ctes', 'chave_cte',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso do CT-e (44 dígitos). Única no sistema.',
               existing_comment='Chave de acesso do CT-e (44 dígitos). Único no sistema.',
               existing_nullable=True)
    op.alter_column('ctes', 'total_rateado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma dos valores já rateados via ItemCte em R$. Deve ser ≤ valor_total_cte.',
               existing_comment='Soma dos valores já rateados para as NFs em R$',
               existing_nullable=False)
    op.alter_column('ctes', 'status',
               existing_type=postgresql.ENUM('IMPORTADO', 'VINCULADO', 'AUDITADO', 'DIVERGENTE', 'CANCELADO', name='statuscte'),
               comment="Status do CT-e no ciclo de vida. CANCELADO substitui o antigo campo booleano 'cancelado'.",
               existing_comment='Status atual do CT-e no ciclo de vida',
               existing_nullable=False)
    op.drop_column('ctes', 'cancelado')
    op.drop_column('ctes', 'total_calculado_nfs')
    op.drop_column('ctes', 'divergencia_total')
    op.alter_column('embarques', 'data_embarque',
               existing_type=sa.DATE(),
               comment='Data prevista/realizada do embarque',
               existing_comment='Data prevista/realizada',
               existing_nullable=False)
    op.alter_column('embarques', 'total_nfs',
               existing_type=sa.INTEGER(),
               comment='Quantidade de NFs no embarque',
               existing_comment='Qtd de NFs',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_real_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma do peso real de todas as NFs em kg',
               existing_comment='Soma peso real',
               existing_nullable=False)
    op.alter_column('embarques', 'total_frete_calculado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do frete calculado de todas as NFs em R$',
               existing_comment='Soma frete calculado',
               existing_nullable=False)
    op.alter_column('embarques', 'total_valor_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do valor fiscal de todas as NFs em R$',
               existing_comment='Soma valor das NFs',
               existing_nullable=False)
    op.alter_column('embarques', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observações livres sobre o embarque',
               existing_comment='Observações livres',
               existing_nullable=True)
    op.drop_column('embarques', 'total_peso_cubado_kg')
    op.alter_column('itens_cte', 'valor_calculado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Snapshot do frete calculado pelo ApuraFrete para esta NF',
               existing_comment='Snapshot do frete_total calculado para esta NF',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_cte', 'valor_calculado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Snapshot do frete_total calculado para esta NF',
               existing_comment='Snapshot do frete calculado pelo ApuraFrete para esta NF',
               existing_nullable=False)
    op.add_column('embarques', sa.Column('total_peso_cubado_kg', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False, comment='Soma peso cubado'))
    op.alter_column('embarques', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observações livres',
               existing_comment='Observações livres sobre o embarque',
               existing_nullable=True)
    op.alter_column('embarques', 'total_valor_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma valor das NFs',
               existing_comment='Soma do valor fiscal de todas as NFs em R$',
               existing_nullable=False)
    op.alter_column('embarques', 'total_frete_calculado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma frete calculado',
               existing_comment='Soma do frete calculado de todas as NFs em R$',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_real_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma peso real',
               existing_comment='Soma do peso real de todas as NFs em kg',
               existing_nullable=False)
    op.alter_column('embarques', 'total_nfs',
               existing_type=sa.INTEGER(),
               comment='Qtd de NFs',
               existing_comment='Quantidade de NFs no embarque',
               existing_nullable=False)
    op.alter_column('embarques', 'data_embarque',
               existing_type=sa.DATE(),
               comment='Data prevista/realizada',
               existing_comment='Data prevista/realizada do embarque',
               existing_nullable=False)
    op.add_column('ctes', sa.Column('divergencia_total', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True, comment='valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais.'))
    op.add_column('ctes', sa.Column('total_calculado_nfs', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False, comment='Soma do frete_total calculado pelo ApuraFrete'))
    op.add_column('ctes', sa.Column('cancelado', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='True = CT-e cancelado'))
    op.alter_column('ctes', 'status',
               existing_type=postgresql.ENUM('IMPORTADO', 'VINCULADO', 'AUDITADO', 'DIVERGENTE', 'CANCELADO', name='statuscte'),
               comment='Status atual do CT-e no ciclo de vida',
               existing_comment="Status do CT-e no ciclo de vida. CANCELADO substitui o antigo campo booleano 'cancelado'.",
               existing_nullable=False)
    op.alter_column('ctes', 'total_rateado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma dos valores já rateados para as NFs em R$',
               existing_comment='Soma dos valores já rateados via ItemCte em R$. Deve ser ≤ valor_total_cte.',
               existing_nullable=False)
    op.alter_column('ctes', 'chave_cte',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso do CT-e (44 dígitos). Único no sistema.',
               existing_comment='Chave de acesso do CT-e (44 dígitos). Única no sistema.',
               existing_nullable=True)
    # ### end Alembic commands ###
