"""initial schema

Revision ID: cfd43fb292cb
Revises: 
Create Date: 2026-07-02 21:14:55.858490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfd43fb292cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('razao_social', sa.String(length=200), nullable=False, comment='Razão social da empresa cliente'),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True, comment='Nome fantasia da empresa cliente'),
    sa.Column('cnpj', sa.String(length=18), nullable=False, comment='CNPJ formatado: 00.000.000/0000-00'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='Identificador amigável único para URL. Ex: acme-logistica'),
    sa.Column('email_contato', sa.String(length=255), nullable=True, comment='E-mail principal de contato da empresa'),
    sa.Column('telefone', sa.String(length=20), nullable=True, comment='Telefone de contato da empresa'),
    sa.Column('plano', sa.String(length=50), nullable=False, comment='Plano contratado: basico | profissional | enterprise'),
    sa.Column('trial', sa.Boolean(), nullable=False, comment='True = empresa em período de trial'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_slug'), 'empresas', ['slug'], unique=True)
    op.create_table('transportadoras',
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='Empresa à qual esta transportadora pertence'),
    sa.Column('razao_social', sa.String(length=200), nullable=False, comment='Razão social da transportadora'),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=True, comment='Nome fantasia da transportadora'),
    sa.Column('cnpj', sa.String(length=18), nullable=True, comment='CNPJ formatado: 00.000.000/0000-00'),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True, comment='Código interno definido pela empresa cliente. Usado como chave de referência na importação de planilhas.'),
    sa.Column('email_contato', sa.String(length=255), nullable=True, comment='E-mail de contato da transportadora'),
    sa.Column('telefone', sa.String(length=20), nullable=True, comment='Telefone de contato da transportadora'),
    sa.Column('observacao', sa.String(length=500), nullable=True, comment='Observações livres sobre a transportadora'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'cnpj', name='uq_transportadora_empresa_cnpj'),
    sa.UniqueConstraint('empresa_id', 'codigo_interno', name='uq_transportadora_empresa_codigo')
    )
    op.create_index(op.f('ix_transportadoras_cnpj'), 'transportadoras', ['cnpj'], unique=False)
    op.create_index(op.f('ix_transportadoras_codigo_interno'), 'transportadoras', ['codigo_interno'], unique=False)
    op.create_index(op.f('ix_transportadoras_empresa_id'), 'transportadoras', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='Empresa à qual este usuário pertence'),
    sa.Column('nome', sa.String(length=150), nullable=False, comment='Nome completo do usuário'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='E-mail do usuário — único por empresa'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt da senha. Nunca texto puro.'),
    sa.Column('perfil', sa.Enum('ADMIN', 'OPERADOR', 'AUDITOR', 'VIEWER', name='perfilacesso'), nullable=False, comment='Perfil de acesso: admin | operador | auditor | viewer'),
    sa.Column('primeiro_acesso', sa.Boolean(), nullable=False, comment='True = usuário deve redefinir senha no próximo login'),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True, comment='Data e hora do último login bem-sucedido'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuario_empresa_email')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_table('auditoria_logs',
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='Empresa (tenant) à qual este log pertence. Garante isolamento multi-tenant.'),
    sa.Column('usuario_id', sa.UUID(), nullable=True, comment='Usuário que realizou a ação. NULL para ações automáticas do sistema.'),
    sa.Column('usuario_email', sa.String(length=255), nullable=True, comment='E-mail do usuário no momento da ação. Snapshot — preserva histórico mesmo se o usuário for alterado/removido.'),
    sa.Column('acao', sa.Enum('CRIAR', 'ATUALIZAR', 'DELETAR', 'IMPORTAR', 'EXPORTAR', 'CALCULAR', 'AUDITAR', 'VINCULAR', 'CANCELAR', 'LOGIN', 'LOGOUT', 'ERRO', name='acaolog'), nullable=False, comment='Tipo de ação realizada'),
    sa.Column('entidade', sa.Enum('EMPRESA', 'USUARIO', 'TRANSPORTADORA', 'TABELA_FRETE', 'FAIXA_PESO', 'EMBARQUE', 'NOTA_FISCAL', 'CTE', 'ITEM_CTE', 'SISTEMA', name='entidadelog'), nullable=False, comment='Entidade (tabela/model) afetada pela ação'),
    sa.Column('entidade_id', sa.UUID(), nullable=True, comment='ID do registro afetado. NULL para ações sem entidade específica (LOGIN, LOGOUT, ERRO de sistema).'),
    sa.Column('entidade_descricao', sa.String(length=255), nullable=True, comment="Descrição legível da entidade afetada. Ex: 'Embarque EMB-2026-001', 'NF 123456'. Snapshot para facilitar leitura do log."),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Estado do registro ANTES da alteração. NULL para ações CRIAR. Formato: JSON com os campos alterados.'),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Estado do registro APÓS a alteração. NULL para ações DELETAR. Formato: JSON com os campos alterados.'),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Contexto adicional livre em JSON. Ex: {arquivo: 'embarque.xlsx', nfs: 42}, {mensagem_erro: '...', traceback: '...'}."),
    sa.Column('ip_origem', sa.String(length=45), nullable=True, comment='IP de origem da requisição. Suporta IPv4 e IPv6 (máx 45 chars).'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User-Agent do cliente HTTP. Para rastreabilidade de acesso.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_logs_acao'), 'auditoria_logs', ['acao'], unique=False)
    op.create_index('ix_auditoria_logs_criado_em', 'auditoria_logs', ['criado_em'], unique=False)
    op.create_index('ix_auditoria_logs_empresa_acao', 'auditoria_logs', ['empresa_id', 'acao'], unique=False)
    op.create_index('ix_auditoria_logs_empresa_entidade', 'auditoria_logs', ['empresa_id', 'entidade', 'entidade_id'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_empresa_id'), 'auditoria_logs', ['empresa_id'], unique=False)
    op.create_index('ix_auditoria_logs_empresa_usuario', 'auditoria_logs', ['empresa_id', 'usuario_id'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_entidade'), 'auditoria_logs', ['entidade'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_entidade_id'), 'auditoria_logs', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_auditoria_logs_usuario_id'), 'auditoria_logs', ['usuario_id'], unique=False)
    op.create_table('tabelas_frete',
    sa.Column('transportadora_id', sa.UUID(), nullable=False, comment='Transportadora à qual esta tabela pertence'),
    sa.Column('nome', sa.String(length=150), nullable=False, comment="Nome descritivo da tabela. Ex: 'Tabela SP 2026'"),
    sa.Column('modalidade', sa.Enum('POR_FAIXA', 'PROGRESSIVO', name='modalidadefrete'), nullable=False, comment='Modalidade de cálculo: por_faixa | progressivo'),
    sa.Column('tabela_ativa', sa.Boolean(), nullable=False, comment='True = tabela vigente para cálculo de frete. Apenas uma tabela ativa por transportadora.'),
    sa.Column('fator_cubagem', sa.Numeric(precision=10, scale=4), nullable=False, comment='Divisor para cálculo do peso cubado. peso_cubado = (C × L × A em cm³) / fator_cubagem. Padrão de mercado: 300.'),
    sa.Column('peso_minimo_kg', sa.Numeric(precision=10, scale=3), nullable=True, comment='Peso mínimo cobrado em kg. Se peso_frete < peso_minimo_kg, usa peso_minimo_kg para o cálculo.'),
    sa.Column('percentual_gris', sa.Numeric(precision=5, scale=4), nullable=True, comment='Percentual de GRIS sobre o valor da NF. Ex: 0.0030 = 0,30%. Aplicado sobre nf_valor.'),
    sa.Column('valor_minimo_gris', sa.Numeric(precision=10, scale=2), nullable=True, comment='Valor mínimo do GRIS em reais. Se GRIS calculado < valor_minimo_gris, cobra valor_minimo_gris.'),
    sa.Column('percentual_advalorem', sa.Numeric(precision=5, scale=4), nullable=True, comment='Percentual de Ad Valorem sobre o valor da NF. Ex: 0.0020 = 0,20%.'),
    sa.Column('valor_despacho', sa.Numeric(precision=10, scale=2), nullable=True, comment='Taxa de despacho fixa por NF em reais.'),
    sa.Column('valor_cte', sa.Numeric(precision=10, scale=2), nullable=True, comment='Taxa de emissão de CT-e fixa por NF em reais.'),
    sa.Column('observacao', sa.String(length=500), nullable=True, comment='Observações livres sobre a tabela de frete'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tabelas_frete_transportadora_id'), 'tabelas_frete', ['transportadora_id'], unique=False)
    op.create_table('embarques',
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='Empresa à qual este embarque pertence'),
    sa.Column('transportadora_id', sa.UUID(), nullable=False, comment='Transportadora responsável pelo embarque'),
    sa.Column('tabela_frete_id', sa.UUID(), nullable=False, comment='Tabela de frete usada no cálculo. Congelada no momento da criação do embarque.'),
    sa.Column('criado_por_id', sa.UUID(), nullable=True, comment='Usuário que criou o embarque'),
    sa.Column('codigo', sa.String(length=50), nullable=False, comment='Código único do embarque por empresa. Ex: EMB-2026-0001. Gerado automaticamente.'),
    sa.Column('data_embarque', sa.Date(), nullable=False, comment='Data prevista ou realizada do embarque'),
    sa.Column('status', sa.Enum('RASCUNHO', 'CALCULADO', 'ENVIADO', 'AUDITADO', 'CANCELADO', name='statusembarque'), nullable=False, comment='Status atual do embarque no ciclo de vida'),
    sa.Column('total_nfs', sa.Integer(), nullable=False, comment='Quantidade total de NFs no embarque. Recalculado automaticamente a cada alteração.'),
    sa.Column('total_peso_real_kg', sa.Numeric(precision=12, scale=3), nullable=False, comment='Soma do peso real de todas as NFs em kg.'),
    sa.Column('total_peso_cubado_kg', sa.Numeric(precision=12, scale=3), nullable=False, comment='Soma do peso cubado de todas as NFs em kg.'),
    sa.Column('total_frete_calculado', sa.Numeric(precision=14, scale=2), nullable=False, comment='Soma do frete calculado de todas as NFs em R$. Atualizado após cada cálculo.'),
    sa.Column('total_valor_nfs', sa.Numeric(precision=14, scale=2), nullable=False, comment='Soma do valor total das NFs em R$. Base para cálculo de GRIS e Ad Valorem.'),
    sa.Column('observacao', sa.Text(), nullable=True, comment='Observações livres sobre o embarque'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tabela_frete_id'], ['tabelas_frete.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_embarque_empresa_codigo')
    )
    op.create_index(op.f('ix_embarques_codigo'), 'embarques', ['codigo'], unique=False)
    op.create_index(op.f('ix_embarques_criado_por_id'), 'embarques', ['criado_por_id'], unique=False)
    op.create_index(op.f('ix_embarques_empresa_id'), 'embarques', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_embarques_status'), 'embarques', ['status'], unique=False)
    op.create_index(op.f('ix_embarques_transportadora_id'), 'embarques', ['transportadora_id'], unique=False)
    op.create_table('faixas_frete',
    sa.Column('tabela_id', sa.UUID(), nullable=False, comment='Tabela de frete à qual esta faixa pertence'),
    sa.Column('peso_de_kg', sa.Numeric(precision=10, scale=3), nullable=False, comment='Limite inferior da faixa (exclusivo) em kg. Primeira faixa deve ser 0.'),
    sa.Column('peso_ate_kg', sa.Numeric(precision=10, scale=3), nullable=True, comment='Limite superior da faixa (inclusivo) em kg. NULL = faixa aberta (sem limite superior).'),
    sa.Column('valor_kg', sa.Numeric(precision=10, scale=4), nullable=False, comment='Valor por kg nesta faixa em reais. Usado tanto em por_faixa quanto em progressivo.'),
    sa.Column('valor_minimo_faixa', sa.Numeric(precision=10, scale=2), nullable=True, comment='Valor mínimo cobrado nesta faixa em reais. Se frete calculado < valor_minimo_faixa, cobra valor_minimo_faixa.'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.CheckConstraint('peso_ate_kg IS NULL OR peso_ate_kg > peso_de_kg', name='ck_faixa_peso_ate_maior_que_de'),
    sa.CheckConstraint('peso_de_kg >= 0', name='ck_faixa_peso_de_nao_negativo'),
    sa.CheckConstraint('valor_kg >= 0', name='ck_faixa_valor_kg_nao_negativo'),
    sa.ForeignKeyConstraint(['tabela_id'], ['tabelas_frete.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faixas_frete_tabela_id'), 'faixas_frete', ['tabela_id'], unique=False)
    op.create_table('ctes',
    sa.Column('transportadora_id', sa.UUID(), nullable=False, comment='Transportadora emissora do CT-e'),
    sa.Column('embarque_id', sa.UUID(), nullable=True, comment='Embarque ao qual este CT-e está vinculado. NULL enquanto não vinculado.'),
    sa.Column('chave_cte', sa.String(length=44), nullable=True, comment='Chave de acesso do CT-e (44 dígitos). Único no sistema. NULL se importado via planilha sem chave disponível.'),
    sa.Column('numero_cte', sa.String(length=20), nullable=False, comment='Número do CT-e conforme emitido pela transportadora.'),
    sa.Column('serie_cte', sa.String(length=5), nullable=True, comment='Série do CT-e. Ex: 001.'),
    sa.Column('data_emissao', sa.Date(), nullable=False, comment='Data de emissão do CT-e'),
    sa.Column('valor_total_cte', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor total cobrado pela transportadora neste CT-e em R$. Base da auditoria.'),
    sa.Column('valor_frete_cte', sa.Numeric(precision=14, scale=2), nullable=True, comment='Valor do frete destacado no CT-e em R$. Pode diferir do valor_total_cte se houver outros encargos no documento.'),
    sa.Column('valor_pedagio', sa.Numeric(precision=12, scale=2), nullable=True, comment='Valor de pedágio destacado no CT-e em R$.'),
    sa.Column('valor_outros', sa.Numeric(precision=12, scale=2), nullable=True, comment='Outros valores cobrados no CT-e em R$. Ex: taxas adicionais, seguros.'),
    sa.Column('total_rateado', sa.Numeric(precision=14, scale=2), nullable=False, comment='Soma dos valores já rateados para as NFs em R$. Deve convergir para valor_total_cte após rateio completo.'),
    sa.Column('total_calculado_nfs', sa.Numeric(precision=14, scale=2), nullable=False, comment='Soma do frete_total calculado pelo ApuraFrete para as NFs vinculadas a este CT-e em R$. Base de comparação para auditoria.'),
    sa.Column('divergencia_total', sa.Numeric(precision=14, scale=2), nullable=True, comment='Diferença entre valor_total_cte e total_calculado_nfs em R$. = valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais. Negativo = cobrado a menos.'),
    sa.Column('origem', sa.Enum('XML', 'PLANILHA', 'MANUAL', name='origemcte'), nullable=False, comment='Como o CT-e foi inserido no sistema'),
    sa.Column('arquivo_origem', sa.String(length=255), nullable=True, comment='Nome do arquivo de origem (XML ou planilha). Para rastreabilidade da importação.'),
    sa.Column('status', sa.Enum('IMPORTADO', 'VINCULADO', 'AUDITADO', 'DIVERGENTE', 'CANCELADO', name='statuscte'), nullable=False, comment='Status atual do CT-e no ciclo de vida'),
    sa.Column('cancelado', sa.Boolean(), nullable=False, comment='True = CT-e cancelado. CT-es cancelados não entram na auditoria.'),
    sa.Column('observacao', sa.Text(), nullable=True, comment='Observações livres sobre o CT-e'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.CheckConstraint('total_rateado >= 0', name='ck_cte_total_rateado_nao_negativo'),
    sa.CheckConstraint('valor_total_cte >= 0', name='ck_cte_valor_total_nao_negativo'),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ctes_chave_cte'), 'ctes', ['chave_cte'], unique=True)
    op.create_index(op.f('ix_ctes_embarque_id'), 'ctes', ['embarque_id'], unique=False)
    op.create_index(op.f('ix_ctes_status'), 'ctes', ['status'], unique=False)
    op.create_index(op.f('ix_ctes_transportadora_id'), 'ctes', ['transportadora_id'], unique=False)
    op.create_table('notas_fiscais',
    sa.Column('embarque_id', sa.UUID(), nullable=False, comment='Embarque ao qual esta NF pertence'),
    sa.Column('numero_nf', sa.String(length=50), nullable=False, comment='Número da nota fiscal. Único dentro do embarque.'),
    sa.Column('serie_nf', sa.String(length=10), nullable=True, comment='Série da nota fiscal. Ex: 001, A, B.'),
    sa.Column('chave_nfe', sa.String(length=44), nullable=True, comment='Chave de acesso da NF-e (44 dígitos). Opcional — usado na auditoria com CT-e.'),
    sa.Column('data_emissao', sa.Date(), nullable=True, comment='Data de emissão da nota fiscal'),
    sa.Column('destinatario_nome', sa.String(length=200), nullable=True, comment='Razão social ou nome do destinatário'),
    sa.Column('destinatario_cnpj_cpf', sa.String(length=18), nullable=True, comment='CNPJ ou CPF do destinatário. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX'),
    sa.Column('destinatario_cidade', sa.String(length=100), nullable=True, comment='Cidade do destinatário'),
    sa.Column('destinatario_uf', sa.String(length=2), nullable=True, comment='UF do destinatário. Ex: SP, RJ, MG.'),
    sa.Column('nf_valor', sa.Numeric(precision=14, scale=2), nullable=False, comment='Valor total da nota fiscal em R$. Base para cálculo de GRIS e Ad Valorem.'),
    sa.Column('peso_real_kg', sa.Numeric(precision=10, scale=3), nullable=False, comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha.'),
    sa.Column('peso_cubado_kg', sa.Numeric(precision=10, scale=3), nullable=True, comment='Peso cubado calculado em kg. = (C × L × A em cm³) / fator_cubagem. NULL se dimensões não informadas.'),
    sa.Column('peso_frete_kg', sa.Numeric(precision=10, scale=3), nullable=True, comment='Peso usado no cálculo do frete. = max(peso_real_kg, peso_cubado_kg). Preenchido pelo engine de cálculo.'),
    sa.Column('quantidade_volumes', sa.Integer(), nullable=True, comment='Quantidade de volumes/caixas da NF'),
    sa.Column('comprimento_cm', sa.Numeric(precision=8, scale=2), nullable=True, comment='Comprimento unitário do volume em cm'),
    sa.Column('largura_cm', sa.Numeric(precision=8, scale=2), nullable=True, comment='Largura unitária do volume em cm'),
    sa.Column('altura_cm', sa.Numeric(precision=8, scale=2), nullable=True, comment='Altura unitária do volume em cm'),
    sa.Column('frete_peso', sa.Numeric(precision=12, scale=2), nullable=True, comment='Valor do frete calculado pelas faixas de peso em R$. Componente principal.'),
    sa.Column('frete_gris', sa.Numeric(precision=12, scale=2), nullable=True, comment='Valor do GRIS calculado em R$. = max(nf_valor × percentual_gris, valor_minimo_gris)'),
    sa.Column('frete_advalorem', sa.Numeric(precision=12, scale=2), nullable=True, comment='Valor do Ad Valorem calculado em R$. = nf_valor × percentual_advalorem'),
    sa.Column('frete_despacho', sa.Numeric(precision=12, scale=2), nullable=True, comment='Taxa de despacho fixa em R$, conforme tabela de frete.'),
    sa.Column('frete_cte', sa.Numeric(precision=12, scale=2), nullable=True, comment='Taxa de emissão de CT-e em R$, conforme tabela de frete.'),
    sa.Column('frete_total', sa.Numeric(precision=12, scale=2), nullable=True, comment='Frete total da NF em R$. = frete_peso + frete_gris + frete_advalorem + frete_despacho + frete_cte'),
    sa.Column('status_calculo', sa.Enum('PENDENTE', 'CALCULADO', 'ERRO', 'IGNORADA', name='statuscalculonf'), nullable=False, comment='Status atual do cálculo de frete desta NF'),
    sa.Column('erro_calculo', sa.Text(), nullable=True, comment='Descrição do erro caso status_calculo = ERRO. Usado para revisão operacional.'),
    sa.Column('observacao', sa.Text(), nullable=True, comment='Observações livres sobre a NF'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.CheckConstraint('frete_total IS NULL OR frete_total >= 0', name='ck_nf_frete_total_nao_negativo'),
    sa.CheckConstraint('nf_valor >= 0', name='ck_nf_valor_nao_negativo'),
    sa.CheckConstraint('peso_cubado_kg IS NULL OR peso_cubado_kg >= 0', name='ck_nf_peso_cubado_nao_negativo'),
    sa.CheckConstraint('peso_real_kg > 0', name='ck_nf_peso_real_positivo'),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embarque_id', 'numero_nf', 'serie_nf', name='uq_nf_embarque_numero_serie')
    )
    op.create_index(op.f('ix_notas_fiscais_chave_nfe'), 'notas_fiscais', ['chave_nfe'], unique=False)
    op.create_index(op.f('ix_notas_fiscais_embarque_id'), 'notas_fiscais', ['embarque_id'], unique=False)
    op.create_index(op.f('ix_notas_fiscais_status_calculo'), 'notas_fiscais', ['status_calculo'], unique=False)
    op.create_table('itens_cte',
    sa.Column('cte_id', sa.UUID(), nullable=False, comment='CT-e ao qual este item pertence'),
    sa.Column('nota_fiscal_id', sa.UUID(), nullable=False, comment='NF vinculada a este item de rateio'),
    sa.Column('valor_rateado', sa.Numeric(precision=12, scale=2), nullable=False, comment='Valor do CT-e rateado para esta NF em R$. Representa o que a transportadora cobrou por esta NF dentro do CT-e.'),
    sa.Column('valor_calculado', sa.Numeric(precision=12, scale=2), nullable=False, comment='Snapshot do frete_total calculado pelo ApuraFrete para esta NF no momento da auditoria. Imutável após geração.'),
    sa.Column('divergencia', sa.Numeric(precision=12, scale=2), nullable=False, comment='Diferença entre o cobrado e o calculado. = valor_rateado - valor_calculado. Positivo = cobrado a mais. Negativo = cobrado a menos.'),
    sa.Column('divergencia_percentual', sa.Numeric(precision=8, scale=4), nullable=True, comment='Divergência percentual sobre valor_calculado. = (divergencia / valor_calculado) × 100. NULL se valor_calculado = 0.'),
    sa.Column('observacao', sa.Text(), nullable=True, comment='Observações ou justificativa da divergência'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único universal (UUID v4)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora de criação do registro'),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Data e hora da última atualização'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='False = registro inativo (soft delete)'),
    sa.CheckConstraint('valor_calculado >= 0', name='ck_item_cte_valor_calculado_nao_negativo'),
    sa.CheckConstraint('valor_rateado >= 0', name='ck_item_cte_valor_rateado_nao_negativo'),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nota_fiscal_id'], ['notas_fiscais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cte_id', 'nota_fiscal_id', name='uq_item_cte_cte_nf')
    )
    op.create_index(op.f('ix_itens_cte_cte_id'), 'itens_cte', ['cte_id'], unique=False)
    op.create_index(op.f('ix_itens_cte_nota_fiscal_id'), 'itens_cte', ['nota_fiscal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_cte_nota_fiscal_id'), table_name='itens_cte')
    op.drop_index(op.f('ix_itens_cte_cte_id'), table_name='itens_cte')
    op.drop_table('itens_cte')
    op.drop_index(op.f('ix_notas_fiscais_status_calculo'), table_name='notas_fiscais')
    op.drop_index(op.f('ix_notas_fiscais_embarque_id'), table_name='notas_fiscais')
    op.drop_index(op.f('ix_notas_fiscais_chave_nfe'), table_name='notas_fiscais')
    op.drop_table('notas_fiscais')
    op.drop_index(op.f('ix_ctes_transportadora_id'), table_name='ctes')
    op.drop_index(op.f('ix_ctes_status'), table_name='ctes')
    op.drop_index(op.f('ix_ctes_embarque_id'), table_name='ctes')
    op.drop_index(op.f('ix_ctes_chave_cte'), table_name='ctes')
    op.drop_table('ctes')
    op.drop_index(op.f('ix_faixas_frete_tabela_id'), table_name='faixas_frete')
    op.drop_table('faixas_frete')
    op.drop_index(op.f('ix_embarques_transportadora_id'), table_name='embarques')
    op.drop_index(op.f('ix_embarques_status'), table_name='embarques')
    op.drop_index(op.f('ix_embarques_empresa_id'), table_name='embarques')
    op.drop_index(op.f('ix_embarques_criado_por_id'), table_name='embarques')
    op.drop_index(op.f('ix_embarques_codigo'), table_name='embarques')
    op.drop_table('embarques')
    op.drop_index(op.f('ix_tabelas_frete_transportadora_id'), table_name='tabelas_frete')
    op.drop_table('tabelas_frete')
    op.drop_index(op.f('ix_auditoria_logs_usuario_id'), table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_entidade_id'), table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_entidade'), table_name='auditoria_logs')
    op.drop_index('ix_auditoria_logs_empresa_usuario', table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_empresa_id'), table_name='auditoria_logs')
    op.drop_index('ix_auditoria_logs_empresa_entidade', table_name='auditoria_logs')
    op.drop_index('ix_auditoria_logs_empresa_acao', table_name='auditoria_logs')
    op.drop_index('ix_auditoria_logs_criado_em', table_name='auditoria_logs')
    op.drop_index(op.f('ix_auditoria_logs_acao'), table_name='auditoria_logs')
    op.drop_table('auditoria_logs')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_transportadoras_empresa_id'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_codigo_interno'), table_name='transportadoras')
    op.drop_index(op.f('ix_transportadoras_cnpj'), table_name='transportadoras')
    op.drop_table('transportadoras')
    op.drop_index(op.f('ix_empresas_slug'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')

    # Remover os tipos ENUM criados nesta migration
    sa.Enum('PENDENTE', 'CALCULADO', 'ERRO', 'IGNORADA', name='statuscalculonf').drop(op.get_bind(), checkfirst=True)
    sa.Enum('IMPORTADO', 'VINCULADO', 'AUDITADO', 'DIVERGENTE', 'CANCELADO', name='statuscte').drop(op.get_bind(), checkfirst=True)
    sa.Enum('XML', 'PLANILHA', 'MANUAL', name='origemcte').drop(op.get_bind(), checkfirst=True)
    sa.Enum('RASCUNHO', 'CALCULADO', 'ENVIADO', 'AUDITADO', 'CANCELADO', name='statusembarque').drop(op.get_bind(), checkfirst=True)
    sa.Enum('POR_FAIXA', 'PROGRESSIVO', name='modalidadefrete').drop(op.get_bind(), checkfirst=True)
    sa.Enum('CRIAR', 'ATUALIZAR', 'DELETAR', 'IMPORTAR', 'EXPORTAR', 'CALCULAR', 'AUDITAR', 'VINCULAR', 'CANCELAR', 'LOGIN', 'LOGOUT', 'ERRO', name='acaolog').drop(op.get_bind(), checkfirst=True)
    sa.Enum('EMPRESA', 'USUARIO', 'TRANSPORTADORA', 'TABELA_FRETE', 'FAIXA_PESO', 'EMBARQUE', 'NOTA_FISCAL', 'CTE', 'ITEM_CTE', 'SISTEMA', name='entidadelog').drop(op.get_bind(), checkfirst=True)
    sa.Enum('ADMIN', 'OPERADOR', 'AUDITOR', 'VIEWER', name='perfilacesso').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
