"""initial schema

Revision ID: d3df23d1bb95
Revises: cfd43fb292cb
Create Date: 2026-07-04 17:14:07.036229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3df23d1bb95'
down_revision: Union[str, None] = 'cfd43fb292cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditoria_logs', 'empresa_id',
               existing_type=sa.UUID(),
               comment='Empresa (tenant) à qual este log pertence',
               existing_comment='Empresa (tenant) à qual este log pertence. Garante isolamento multi-tenant.',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'usuario_id',
               existing_type=sa.UUID(),
               comment='Usuário que realizou a ação. NULL = ação automática.',
               existing_comment='Usuário que realizou a ação. NULL para ações automáticas do sistema.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'usuario_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Snapshot do e-mail do usuário no momento da ação',
               existing_comment='E-mail do usuário no momento da ação. Snapshot — preserva histórico mesmo se o usuário for alterado/removido.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade',
               existing_type=postgresql.ENUM('EMPRESA', 'USUARIO', 'TRANSPORTADORA', 'TABELA_FRETE', 'FAIXA_PESO', 'EMBARQUE', 'NOTA_FISCAL', 'CTE', 'ITEM_CTE', 'SISTEMA', name='entidadelog'),
               comment='Entidade afetada pela ação',
               existing_comment='Entidade (tabela/model) afetada pela ação',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'entidade_id',
               existing_type=sa.UUID(),
               comment='ID do registro afetado. NULL para ações sem entidade.',
               existing_comment='ID do registro afetado. NULL para ações sem entidade específica (LOGIN, LOGOUT, ERRO de sistema).',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade_descricao',
               existing_type=sa.VARCHAR(length=255),
               comment='Descrição legível da entidade afetada',
               existing_comment="Descrição legível da entidade afetada. Ex: 'Embarque EMB-2026-001', 'NF 123456'. Snapshot para facilitar leitura do log.",
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'dados_anteriores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estado do registro ANTES da alteração',
               existing_comment='Estado do registro ANTES da alteração. NULL para ações CRIAR. Formato: JSON com os campos alterados.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'dados_novos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estado do registro APÓS a alteração',
               existing_comment='Estado do registro APÓS a alteração. NULL para ações DELETAR. Formato: JSON com os campos alterados.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'detalhes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Contexto adicional livre em JSON',
               existing_comment="Contexto adicional livre em JSON. Ex: {arquivo: 'embarque.xlsx', nfs: 42}, {mensagem_erro: '...', traceback: '...'}.",
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'ip_origem',
               existing_type=sa.VARCHAR(length=45),
               comment='IP de origem da requisição',
               existing_comment='IP de origem da requisição. Suporta IPv4 e IPv6 (máx 45 chars).',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               comment='User-Agent do cliente HTTP',
               existing_comment='User-Agent do cliente HTTP. Para rastreabilidade de acesso.',
               existing_nullable=True)
    op.alter_column('ctes', 'embarque_id',
               existing_type=sa.UUID(),
               comment='Embarque ao qual este CT-e está vinculado',
               existing_comment='Embarque ao qual este CT-e está vinculado. NULL enquanto não vinculado.',
               existing_nullable=True)
    op.alter_column('ctes', 'chave_cte',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso do CT-e (44 dígitos). Único no sistema.',
               existing_comment='Chave de acesso do CT-e (44 dígitos). Único no sistema. NULL se importado via planilha sem chave disponível.',
               existing_nullable=True)
    op.alter_column('ctes', 'numero_cte',
               existing_type=sa.VARCHAR(length=20),
               comment='Número do CT-e',
               existing_comment='Número do CT-e conforme emitido pela transportadora.',
               existing_nullable=False)
    op.alter_column('ctes', 'serie_cte',
               existing_type=sa.VARCHAR(length=5),
               comment='Série do CT-e. Ex: 001',
               existing_comment='Série do CT-e. Ex: 001.',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_total_cte',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor total cobrado em R$. Base da auditoria.',
               existing_comment='Valor total cobrado pela transportadora neste CT-e em R$. Base da auditoria.',
               existing_nullable=False)
    op.alter_column('ctes', 'valor_frete_cte',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor do frete destacado no CT-e em R$',
               existing_comment='Valor do frete destacado no CT-e em R$. Pode diferir do valor_total_cte se houver outros encargos no documento.',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_pedagio',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Valor de pedágio destacado no CT-e em R$',
               existing_comment='Valor de pedágio destacado no CT-e em R$.',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_outros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Outros valores cobrados no CT-e em R$',
               existing_comment='Outros valores cobrados no CT-e em R$. Ex: taxas adicionais, seguros.',
               existing_nullable=True)
    op.alter_column('ctes', 'total_rateado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma dos valores já rateados para as NFs em R$',
               existing_comment='Soma dos valores já rateados para as NFs em R$. Deve convergir para valor_total_cte após rateio completo.',
               existing_nullable=False)
    op.alter_column('ctes', 'total_calculado_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do frete_total calculado pelo ApuraFrete',
               existing_comment='Soma do frete_total calculado pelo ApuraFrete para as NFs vinculadas a este CT-e em R$. Base de comparação para auditoria.',
               existing_nullable=False)
    op.alter_column('ctes', 'divergencia_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais.',
               existing_comment='Diferença entre valor_total_cte e total_calculado_nfs em R$. = valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais. Negativo = cobrado a menos.',
               existing_nullable=True)
    op.alter_column('ctes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do arquivo de origem (XML ou planilha)',
               existing_comment='Nome do arquivo de origem (XML ou planilha). Para rastreabilidade da importação.',
               existing_nullable=True)
    op.alter_column('ctes', 'cancelado',
               existing_type=sa.BOOLEAN(),
               comment='True = CT-e cancelado',
               existing_comment='True = CT-e cancelado. CT-es cancelados não entram na auditoria.',
               existing_nullable=False)
    op.alter_column('embarques', 'tabela_frete_id',
               existing_type=sa.UUID(),
               comment='Tabela de frete congelada no momento da criação',
               existing_comment='Tabela de frete usada no cálculo. Congelada no momento da criação do embarque.',
               existing_nullable=False)
    op.alter_column('embarques', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único por empresa. Ex: EMB-2026-0001',
               existing_comment='Código único do embarque por empresa. Ex: EMB-2026-0001. Gerado automaticamente.',
               existing_nullable=False)
    op.alter_column('embarques', 'data_embarque',
               existing_type=sa.DATE(),
               comment='Data prevista/realizada',
               existing_comment='Data prevista ou realizada do embarque',
               existing_nullable=False)
    op.alter_column('embarques', 'status',
               existing_type=postgresql.ENUM('RASCUNHO', 'CALCULADO', 'ENVIADO', 'AUDITADO', 'CANCELADO', name='statusembarque'),
               comment='Status atual do ciclo de vida',
               existing_comment='Status atual do embarque no ciclo de vida',
               existing_nullable=False)
    op.alter_column('embarques', 'total_nfs',
               existing_type=sa.INTEGER(),
               comment='Qtd de NFs',
               existing_comment='Quantidade total de NFs no embarque. Recalculado automaticamente a cada alteração.',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_real_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma peso real',
               existing_comment='Soma do peso real de todas as NFs em kg.',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_cubado_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma peso cubado',
               existing_comment='Soma do peso cubado de todas as NFs em kg.',
               existing_nullable=False)
    op.alter_column('embarques', 'total_frete_calculado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma frete calculado',
               existing_comment='Soma do frete calculado de todas as NFs em R$. Atualizado após cada cálculo.',
               existing_nullable=False)
    op.alter_column('embarques', 'total_valor_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma valor das NFs',
               existing_comment='Soma do valor total das NFs em R$. Base para cálculo de GRIS e Ad Valorem.',
               existing_nullable=False)
    op.alter_column('embarques', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observações livres',
               existing_comment='Observações livres sobre o embarque',
               existing_nullable=True)
    op.alter_column('itens_cte', 'valor_rateado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Valor do CT-e rateado para esta NF em R$',
               existing_comment='Valor do CT-e rateado para esta NF em R$. Representa o que a transportadora cobrou por esta NF dentro do CT-e.',
               existing_nullable=False)
    op.alter_column('itens_cte', 'valor_calculado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Snapshot do frete_total calculado para esta NF',
               existing_comment='Snapshot do frete_total calculado pelo ApuraFrete para esta NF no momento da auditoria. Imutável após geração.',
               existing_nullable=False)
    op.alter_column('itens_cte', 'divergencia',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='valor_rateado - valor_calculado. Positivo = cobrado a mais.',
               existing_comment='Diferença entre o cobrado e o calculado. = valor_rateado - valor_calculado. Positivo = cobrado a mais. Negativo = cobrado a menos.',
               existing_nullable=False)
    op.alter_column('itens_cte', 'divergencia_percentual',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='(divergencia / valor_calculado) × 100',
               existing_comment='Divergência percentual sobre valor_calculado. = (divergencia / valor_calculado) × 100. NULL se valor_calculado = 0.',
               existing_nullable=True)
    op.alter_column('transportadoras', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social',
               existing_comment='Razão social da transportadora',
               existing_nullable=False)
    op.alter_column('transportadoras', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia',
               existing_comment='Nome fantasia da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado',
               existing_comment='CNPJ formatado: 00.000.000/0000-00',
               existing_nullable=True)
    op.alter_column('transportadoras', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='Código interno usado na importação de planilhas',
               existing_comment='Código interno definido pela empresa cliente. Usado como chave de referência na importação de planilhas.',
               existing_nullable=True)
    op.alter_column('transportadoras', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail de contato',
               existing_comment='E-mail de contato da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato',
               existing_comment='Telefone de contato da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'observacao',
               existing_type=sa.VARCHAR(length=500),
               comment='Observações livres',
               existing_comment='Observações livres sobre a transportadora',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transportadoras', 'observacao',
               existing_type=sa.VARCHAR(length=500),
               comment='Observações livres sobre a transportadora',
               existing_comment='Observações livres',
               existing_nullable=True)
    op.alter_column('transportadoras', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato da transportadora',
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('transportadoras', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail de contato da transportadora',
               existing_comment='E-mail de contato',
               existing_nullable=True)
    op.alter_column('transportadoras', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='Código interno definido pela empresa cliente. Usado como chave de referência na importação de planilhas.',
               existing_comment='Código interno usado na importação de planilhas',
               existing_nullable=True)
    op.alter_column('transportadoras', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado: 00.000.000/0000-00',
               existing_comment='CNPJ formatado',
               existing_nullable=True)
    op.alter_column('transportadoras', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia da transportadora',
               existing_comment='Nome fantasia',
               existing_nullable=True)
    op.alter_column('transportadoras', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social da transportadora',
               existing_comment='Razão social',
               existing_nullable=False)
    op.alter_column('itens_cte', 'divergencia_percentual',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Divergência percentual sobre valor_calculado. = (divergencia / valor_calculado) × 100. NULL se valor_calculado = 0.',
               existing_comment='(divergencia / valor_calculado) × 100',
               existing_nullable=True)
    op.alter_column('itens_cte', 'divergencia',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Diferença entre o cobrado e o calculado. = valor_rateado - valor_calculado. Positivo = cobrado a mais. Negativo = cobrado a menos.',
               existing_comment='valor_rateado - valor_calculado. Positivo = cobrado a mais.',
               existing_nullable=False)
    op.alter_column('itens_cte', 'valor_calculado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Snapshot do frete_total calculado pelo ApuraFrete para esta NF no momento da auditoria. Imutável após geração.',
               existing_comment='Snapshot do frete_total calculado para esta NF',
               existing_nullable=False)
    op.alter_column('itens_cte', 'valor_rateado',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Valor do CT-e rateado para esta NF em R$. Representa o que a transportadora cobrou por esta NF dentro do CT-e.',
               existing_comment='Valor do CT-e rateado para esta NF em R$',
               existing_nullable=False)
    op.alter_column('embarques', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observações livres sobre o embarque',
               existing_comment='Observações livres',
               existing_nullable=True)
    op.alter_column('embarques', 'total_valor_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do valor total das NFs em R$. Base para cálculo de GRIS e Ad Valorem.',
               existing_comment='Soma valor das NFs',
               existing_nullable=False)
    op.alter_column('embarques', 'total_frete_calculado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do frete calculado de todas as NFs em R$. Atualizado após cada cálculo.',
               existing_comment='Soma frete calculado',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_cubado_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma do peso cubado de todas as NFs em kg.',
               existing_comment='Soma peso cubado',
               existing_nullable=False)
    op.alter_column('embarques', 'total_peso_real_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               comment='Soma do peso real de todas as NFs em kg.',
               existing_comment='Soma peso real',
               existing_nullable=False)
    op.alter_column('embarques', 'total_nfs',
               existing_type=sa.INTEGER(),
               comment='Quantidade total de NFs no embarque. Recalculado automaticamente a cada alteração.',
               existing_comment='Qtd de NFs',
               existing_nullable=False)
    op.alter_column('embarques', 'status',
               existing_type=postgresql.ENUM('RASCUNHO', 'CALCULADO', 'ENVIADO', 'AUDITADO', 'CANCELADO', name='statusembarque'),
               comment='Status atual do embarque no ciclo de vida',
               existing_comment='Status atual do ciclo de vida',
               existing_nullable=False)
    op.alter_column('embarques', 'data_embarque',
               existing_type=sa.DATE(),
               comment='Data prevista ou realizada do embarque',
               existing_comment='Data prevista/realizada',
               existing_nullable=False)
    op.alter_column('embarques', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               comment='Código único do embarque por empresa. Ex: EMB-2026-0001. Gerado automaticamente.',
               existing_comment='Código único por empresa. Ex: EMB-2026-0001',
               existing_nullable=False)
    op.alter_column('embarques', 'tabela_frete_id',
               existing_type=sa.UUID(),
               comment='Tabela de frete usada no cálculo. Congelada no momento da criação do embarque.',
               existing_comment='Tabela de frete congelada no momento da criação',
               existing_nullable=False)
    op.alter_column('ctes', 'cancelado',
               existing_type=sa.BOOLEAN(),
               comment='True = CT-e cancelado. CT-es cancelados não entram na auditoria.',
               existing_comment='True = CT-e cancelado',
               existing_nullable=False)
    op.alter_column('ctes', 'arquivo_origem',
               existing_type=sa.VARCHAR(length=255),
               comment='Nome do arquivo de origem (XML ou planilha). Para rastreabilidade da importação.',
               existing_comment='Nome do arquivo de origem (XML ou planilha)',
               existing_nullable=True)
    op.alter_column('ctes', 'divergencia_total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Diferença entre valor_total_cte e total_calculado_nfs em R$. = valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais. Negativo = cobrado a menos.',
               existing_comment='valor_total_cte - total_calculado_nfs. Positivo = cobrado a mais.',
               existing_nullable=True)
    op.alter_column('ctes', 'total_calculado_nfs',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma do frete_total calculado pelo ApuraFrete para as NFs vinculadas a este CT-e em R$. Base de comparação para auditoria.',
               existing_comment='Soma do frete_total calculado pelo ApuraFrete',
               existing_nullable=False)
    op.alter_column('ctes', 'total_rateado',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Soma dos valores já rateados para as NFs em R$. Deve convergir para valor_total_cte após rateio completo.',
               existing_comment='Soma dos valores já rateados para as NFs em R$',
               existing_nullable=False)
    op.alter_column('ctes', 'valor_outros',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Outros valores cobrados no CT-e em R$. Ex: taxas adicionais, seguros.',
               existing_comment='Outros valores cobrados no CT-e em R$',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_pedagio',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Valor de pedágio destacado no CT-e em R$.',
               existing_comment='Valor de pedágio destacado no CT-e em R$',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_frete_cte',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor do frete destacado no CT-e em R$. Pode diferir do valor_total_cte se houver outros encargos no documento.',
               existing_comment='Valor do frete destacado no CT-e em R$',
               existing_nullable=True)
    op.alter_column('ctes', 'valor_total_cte',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment='Valor total cobrado pela transportadora neste CT-e em R$. Base da auditoria.',
               existing_comment='Valor total cobrado em R$. Base da auditoria.',
               existing_nullable=False)
    op.alter_column('ctes', 'serie_cte',
               existing_type=sa.VARCHAR(length=5),
               comment='Série do CT-e. Ex: 001.',
               existing_comment='Série do CT-e. Ex: 001',
               existing_nullable=True)
    op.alter_column('ctes', 'numero_cte',
               existing_type=sa.VARCHAR(length=20),
               comment='Número do CT-e conforme emitido pela transportadora.',
               existing_comment='Número do CT-e',
               existing_nullable=False)
    op.alter_column('ctes', 'chave_cte',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso do CT-e (44 dígitos). Único no sistema. NULL se importado via planilha sem chave disponível.',
               existing_comment='Chave de acesso do CT-e (44 dígitos). Único no sistema.',
               existing_nullable=True)
    op.alter_column('ctes', 'embarque_id',
               existing_type=sa.UUID(),
               comment='Embarque ao qual este CT-e está vinculado. NULL enquanto não vinculado.',
               existing_comment='Embarque ao qual este CT-e está vinculado',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=512),
               comment='User-Agent do cliente HTTP. Para rastreabilidade de acesso.',
               existing_comment='User-Agent do cliente HTTP',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'ip_origem',
               existing_type=sa.VARCHAR(length=45),
               comment='IP de origem da requisição. Suporta IPv4 e IPv6 (máx 45 chars).',
               existing_comment='IP de origem da requisição',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'detalhes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Contexto adicional livre em JSON. Ex: {arquivo: 'embarque.xlsx', nfs: 42}, {mensagem_erro: '...', traceback: '...'}.",
               existing_comment='Contexto adicional livre em JSON',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'dados_novos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estado do registro APÓS a alteração. NULL para ações DELETAR. Formato: JSON com os campos alterados.',
               existing_comment='Estado do registro APÓS a alteração',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'dados_anteriores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estado do registro ANTES da alteração. NULL para ações CRIAR. Formato: JSON com os campos alterados.',
               existing_comment='Estado do registro ANTES da alteração',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade_descricao',
               existing_type=sa.VARCHAR(length=255),
               comment="Descrição legível da entidade afetada. Ex: 'Embarque EMB-2026-001', 'NF 123456'. Snapshot para facilitar leitura do log.",
               existing_comment='Descrição legível da entidade afetada',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade_id',
               existing_type=sa.UUID(),
               comment='ID do registro afetado. NULL para ações sem entidade específica (LOGIN, LOGOUT, ERRO de sistema).',
               existing_comment='ID do registro afetado. NULL para ações sem entidade.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'entidade',
               existing_type=postgresql.ENUM('EMPRESA', 'USUARIO', 'TRANSPORTADORA', 'TABELA_FRETE', 'FAIXA_PESO', 'EMBARQUE', 'NOTA_FISCAL', 'CTE', 'ITEM_CTE', 'SISTEMA', name='entidadelog'),
               comment='Entidade (tabela/model) afetada pela ação',
               existing_comment='Entidade afetada pela ação',
               existing_nullable=False)
    op.alter_column('auditoria_logs', 'usuario_email',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail do usuário no momento da ação. Snapshot — preserva histórico mesmo se o usuário for alterado/removido.',
               existing_comment='Snapshot do e-mail do usuário no momento da ação',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'usuario_id',
               existing_type=sa.UUID(),
               comment='Usuário que realizou a ação. NULL para ações automáticas do sistema.',
               existing_comment='Usuário que realizou a ação. NULL = ação automática.',
               existing_nullable=True)
    op.alter_column('auditoria_logs', 'empresa_id',
               existing_type=sa.UUID(),
               comment='Empresa (tenant) à qual este log pertence. Garante isolamento multi-tenant.',
               existing_comment='Empresa (tenant) à qual este log pertence',
               existing_nullable=False)
    # ### end Alembic commands ###
