"""unifica_empresa_tenant_terceiro

Revision ID: eec6940b1127
Revises: 28aaa21c70c2
Create Date: 2026-07-11 12:33:13.757516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eec6940b1127'
down_revision: Union[str, None] = '28aaa21c70c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('tipo', sa.String(length=20), nullable=False, comment='tenant | terceiro'))
    op.add_column('empresas', sa.Column('codigo_terceiro', sa.String(length=50), nullable=True, comment='COD CLIENTE da planilha (ex: 000123)'))
    op.add_column('empresas', sa.Column('tipo_pessoa', sa.String(length=20), nullable=True, comment='remetente | destinatario | ambos (apenas para terceiros)'))
    op.alter_column('empresas', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social (tenant ou terceiro)',
               existing_comment='Razão social da empresa cliente',
               existing_nullable=False)
    op.alter_column('empresas', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia',
               existing_comment='Nome fantasia da empresa cliente',
               existing_nullable=True)
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado: 00.000.000/0000-00 (único global)',
               existing_comment='CNPJ formatado: 00.000.000/0000-00',
               existing_nullable=False)
    op.alter_column('empresas', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail principal de contato',
               existing_comment='E-mail principal de contato da empresa',
               existing_nullable=True)
    op.alter_column('empresas', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato',
               existing_comment='Telefone de contato da empresa',
               existing_nullable=True)
    op.alter_column('empresas', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               comment='Identificador URL do tenant. Ex: acme-logistica (NULL para terceiros)',
               existing_comment='Identificador amigável único para URL. Ex: acme-logistica')
    op.alter_column('empresas', 'plano',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Plano do tenant: basico | profissional | enterprise (NULL para terceiros)',
               existing_comment='Plano contratado: basico | profissional | enterprise')
    op.alter_column('empresas', 'trial',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='True = tenant em período de trial (NULL para terceiros)',
               existing_comment='True = empresa em período de trial')
    op.create_index(op.f('ix_empresas_codigo_terceiro'), 'empresas', ['codigo_terceiro'], unique=False)
    op.create_index(op.f('ix_empresas_tipo'), 'empresas', ['tipo'], unique=False)
    op.create_index('ix_empresas_tipo_codigo_terceiro', 'empresas', ['tipo', 'codigo_terceiro'], unique=False)
    op.alter_column('faixas_frete', 'valor_kg',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Valor por kg nesta faixa em reais. No MVP, usado apenas na faixa 2 (30 kg → ∞) como adicional por kg excedente.',
               existing_comment='Valor por kg nesta faixa em reais. Usado tanto em por_faixa quanto em progressivo.',
               existing_nullable=False)
    op.alter_column('faixas_frete', 'valor_minimo_faixa',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor mínimo cobrado nesta faixa em reais. No MVP, usado apenas na faixa 1 (0 → 30 kg) como preço fixo para fretes até 30 kg.',
               existing_comment='Valor mínimo cobrado nesta faixa em reais. Se frete calculado < valor_minimo_faixa, cobra valor_minimo_faixa.',
               existing_nullable=True)
    op.add_column('notas_fiscais', sa.Column('cod_cliente', sa.String(length=50), nullable=False, comment='Código do cliente destino. Origem: coluna COD CLIENTE.'))
    op.add_column('notas_fiscais', sa.Column('cliente_destino', sa.String(length=200), nullable=False, comment='Nome do cliente destino. Origem: coluna CLIENTE DESTINO.'))
    op.add_column('notas_fiscais', sa.Column('cnpj_destino', sa.String(length=14), nullable=False, comment='CNPJ do destinatário (14 dígitos, sem máscara). Origem: coluna CNPJ DESTINO.'))
    op.add_column('notas_fiscais', sa.Column('cidade_destino', sa.String(length=100), nullable=False, comment='Cidade de destino. Derivado de CIDADE - UF DESTINO (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('uf_destino', sa.String(length=2), nullable=False, comment='UF de destino (2 letras). Ex: SP, RJ, MG. Derivado de CIDADE - UF DESTINO (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('cidade_destino_raw', sa.String(length=200), nullable=True, comment='Valor original de CIDADE - UF DESTINO antes da normalização (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('cod_remetente', sa.String(length=50), nullable=False, comment='Código do remetente. Origem: coluna COD REMETENTE.'))
    op.add_column('notas_fiscais', sa.Column('cliente_remetente', sa.String(length=200), nullable=False, comment='Nome do remetente. Origem: coluna CLIENTE REMETENTE.'))
    op.add_column('notas_fiscais', sa.Column('cnpj_remetente', sa.String(length=14), nullable=False, comment='CNPJ do emitente (14 dígitos, sem máscara). Origem: coluna CNPJ REMETENTE.'))
    op.add_column('notas_fiscais', sa.Column('cidade_remetente', sa.String(length=100), nullable=False, comment='Cidade de origem. Derivado de CIDADE - UF REMETENTE (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('uf_remetente', sa.String(length=2), nullable=False, comment='UF de origem (2 letras). Derivado de CIDADE - UF REMETENTE (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('cidade_remetente_raw', sa.String(length=200), nullable=True, comment='Valor original de CIDADE - UF REMETENTE antes da normalização (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('cod_produto', sa.String(length=100), nullable=False, comment='SKU do produto (catálogo). Origem: coluna COD PRODUTO. Deve existir no cadastro (Seção 1.2).'))
    op.add_column('notas_fiscais', sa.Column('qtd_cx', sa.Integer(), nullable=False, comment='Quantidade de caixas/volumes. Origem: coluna QTD CX. Deve ser ≥ 1 (Seção 4.2).'))
    op.add_column('notas_fiscais', sa.Column('peso_total_kg', sa.Numeric(precision=10, scale=3), nullable=False, comment='Peso total da NF em kg. Fórmula: QTD_CX × produto.peso_real_kg (Seção 3.1). Armazenado para auditoria e reprocessabilidade.'))
    op.add_column('notas_fiscais', sa.Column('transportadora_id', sa.UUID(), nullable=True, comment='Transportadora selecionada manualmente. NULL = ainda não selecionada (Seção 6.1).'))
    op.add_column('notas_fiscais', sa.Column('valor_calculado', sa.Numeric(precision=12, scale=2), nullable=True, comment='Valor do frete calculado em R$ (fórmula da Seção 6.4).'))
    op.add_column('notas_fiscais', sa.Column('prazo_dias', sa.Integer(), nullable=True, comment='Prazo de entrega em dias, conforme tabela (informativo — Seção 7.2).'))
    op.add_column('notas_fiscais', sa.Column('preco_ate_30kg_usado', sa.Numeric(precision=12, scale=2), nullable=True, comment='Snapshot: preço até 30kg usado no cálculo.'))
    op.add_column('notas_fiscais', sa.Column('valor_kg_adicional_usado', sa.Numeric(precision=12, scale=2), nullable=True, comment='Snapshot: valor do kg adicional usado no cálculo.'))
    op.add_column('notas_fiscais', sa.Column('peso_kg_usado', sa.Numeric(precision=10, scale=3), nullable=True, comment='Snapshot: peso em kg usado no cálculo (= peso_total_kg no momento do cálculo).'))
    op.add_column('notas_fiscais', sa.Column('centro_custo', sa.Text(), nullable=True, comment='Campo livre. Origem: coluna CENTRO DE CUSTO.'))
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha.',
               existing_comment='Numero da nota fiscal. Unico dentro do embarque.',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'serie_nf',
               existing_type=sa.VARCHAR(length=10),
               comment='Série da nota fiscal. Ex: 001, A, B.',
               existing_comment='Serie da nota fiscal. Ex: 001, A, B.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'chave_nfe',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso da NF-e (44 dígitos). Usada na auditoria CT-e (Seção 8.2).',
               existing_comment='Chave de acesso da NF-e (44 digitos). Opcional — usado na auditoria com CT-e.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'data_emissao',
               existing_type=sa.DATE(),
               comment='Data de emissão da nota fiscal',
               existing_comment='Data de emissao da nota fiscal',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'nf_valor',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=True,
               comment='Valor total da nota fiscal em R$ (informativo).',
               existing_comment='Valor total da nota fiscal em R$.')
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('pendente', 'calculado', 'erro', 'ignorada', 'sem_tabela', 'sem_transportadora', name='statuscalculonf'),
               comment='Status do cálculo de frete (Seção 6.7).',
               existing_comment='Status atual do calculo de frete desta NF',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'erro_calculo',
               existing_type=sa.TEXT(),
               comment='Descrição do erro (status_calculo = ERRO).',
               existing_comment='Descricao do erro caso status_calculo = ERRO. Usado para revisao operacional.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Campo livre. Origem: coluna OBSERVAÇÃO.',
               existing_comment='Observacoes livres sobre a NF',
               existing_nullable=True)
    op.create_index(op.f('ix_notas_fiscais_transportadora_id'), 'notas_fiscais', ['transportadora_id'], unique=False)
    op.create_foreign_key(None, 'notas_fiscais', 'transportadoras', ['transportadora_id'], ['id'], ondelete='SET NULL')
    op.drop_column('notas_fiscais', 'destinatario_uf')
    op.drop_column('notas_fiscais', 'peso_real_kg')
    op.drop_column('notas_fiscais', 'destinatario_nome')
    op.drop_column('notas_fiscais', 'frete_total')
    op.drop_column('notas_fiscais', 'destinatario_cnpj_cpf')
    op.drop_column('notas_fiscais', 'frete_cte')
    op.drop_column('notas_fiscais', 'destinatario_cidade')
    op.drop_column('notas_fiscais', 'frete_peso')
    op.drop_column('notas_fiscais', 'quantidade_volumes')
    op.drop_column('tabelas_frete', 'valor_minimo_gris')
    op.drop_column('tabelas_frete', 'valor_cte')
    op.drop_column('tabelas_frete', 'percentual_gris')
    op.drop_column('tabelas_frete', 'percentual_advalorem')
    op.drop_column('tabelas_frete', 'fator_cubagem')
    op.drop_column('tabelas_frete', 'valor_despacho')
    op.drop_column('tabelas_frete', 'peso_minimo_kg')
    op.alter_column('transportadoras', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social da transportadora',
               existing_comment='Razão social',
               existing_nullable=False)
    op.alter_column('transportadoras', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia da transportadora',
               existing_comment='Nome fantasia',
               existing_nullable=True)
    op.alter_column('transportadoras', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado (XX.XXX.XXX/XXXX-XX)',
               existing_comment='CNPJ formatado',
               existing_nullable=True)
    op.alter_column('transportadoras', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='Código interno usado na importação de planilhas. Origem: coluna TRANSPORTADORA (MVP Seção 4.1).',
               existing_comment='Código interno usado na importação de planilhas',
               existing_nullable=True)
    op.alter_column('transportadoras', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail de contato da transportadora',
               existing_comment='E-mail de contato',
               existing_nullable=True)
    op.alter_column('transportadoras', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato da transportadora',
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('transportadoras', 'observacao',
               existing_type=sa.VARCHAR(length=500),
               comment='Observações livres sobre a transportadora',
               existing_comment='Observações livres',
               existing_nullable=True)
    op.alter_column('transportadoras', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='Se False, transportadora não pode ser selecionada em novos embarques (Seção 1.3).',
               existing_comment='Se False, transportadora não pode ser selecionada em novos embarques',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transportadoras', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='Se False, transportadora não pode ser selecionada em novos embarques',
               existing_comment='Se False, transportadora não pode ser selecionada em novos embarques (Seção 1.3).',
               existing_nullable=False)
    op.alter_column('transportadoras', 'observacao',
               existing_type=sa.VARCHAR(length=500),
               comment='Observações livres',
               existing_comment='Observações livres sobre a transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato',
               existing_comment='Telefone de contato da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail de contato',
               existing_comment='E-mail de contato da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='Código interno usado na importação de planilhas',
               existing_comment='Código interno usado na importação de planilhas. Origem: coluna TRANSPORTADORA (MVP Seção 4.1).',
               existing_nullable=True)
    op.alter_column('transportadoras', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado',
               existing_comment='CNPJ formatado (XX.XXX.XXX/XXXX-XX)',
               existing_nullable=True)
    op.alter_column('transportadoras', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia',
               existing_comment='Nome fantasia da transportadora',
               existing_nullable=True)
    op.alter_column('transportadoras', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social',
               existing_comment='Razão social da transportadora',
               existing_nullable=False)
    op.add_column('tabelas_frete', sa.Column('peso_minimo_kg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True, comment='Peso mínimo cobrado em kg. Se peso_frete < peso_minimo_kg, usa peso_minimo_kg para o cálculo.'))
    op.add_column('tabelas_frete', sa.Column('valor_despacho', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Taxa de despacho fixa por NF em reais.'))
    op.add_column('tabelas_frete', sa.Column('fator_cubagem', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False, comment='Divisor para cálculo do peso cubado. peso_cubado = (C × L × A em cm³) / fator_cubagem. Padrão de mercado: 300.'))
    op.add_column('tabelas_frete', sa.Column('percentual_advalorem', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Percentual de Ad Valorem sobre o valor da NF. Ex: 0.0020 = 0,20%.'))
    op.add_column('tabelas_frete', sa.Column('percentual_gris', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True, comment='Percentual de GRIS sobre o valor da NF. Ex: 0.0030 = 0,30%. Aplicado sobre nf_valor.'))
    op.add_column('tabelas_frete', sa.Column('valor_cte', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Taxa de emissão de CT-e fixa por NF em reais.'))
    op.add_column('tabelas_frete', sa.Column('valor_minimo_gris', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Valor mínimo do GRIS em reais. Se GRIS calculado < valor_minimo_gris, cobra valor_minimo_gris.'))
    op.add_column('notas_fiscais', sa.Column('quantidade_volumes', sa.INTEGER(), autoincrement=False, nullable=True, comment='Quantidade de volumes/caixas da NF'))
    op.add_column('notas_fiscais', sa.Column('frete_peso', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Valor do frete calculado pelas faixas de peso em R$. Componente principal.'))
    op.add_column('notas_fiscais', sa.Column('destinatario_cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Cidade do destinatario'))
    op.add_column('notas_fiscais', sa.Column('frete_cte', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Taxa de emissao de CT-e em R$, conforme tabela de frete.'))
    op.add_column('notas_fiscais', sa.Column('destinatario_cnpj_cpf', sa.VARCHAR(length=18), autoincrement=False, nullable=True, comment='CNPJ ou CPF do destinatario. Formato: XX.XXX.XXX/XXXX-XX ou XXX.XXX.XXX-XX'))
    op.add_column('notas_fiscais', sa.Column('frete_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True, comment='Frete total da NF em R$. = frete_peso + frete_cte'))
    op.add_column('notas_fiscais', sa.Column('destinatario_nome', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='Razao social ou nome do destinatario'))
    op.add_column('notas_fiscais', sa.Column('peso_real_kg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False, comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. E a metrica unica de peso para calculo de frete — o projeto NAO utiliza cubagem.'))
    op.add_column('notas_fiscais', sa.Column('destinatario_uf', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='UF do destinatario. Ex: SP, RJ, MG.'))
    op.drop_constraint(None, 'notas_fiscais', type_='foreignkey')
    op.drop_index(op.f('ix_notas_fiscais_transportadora_id'), table_name='notas_fiscais')
    op.alter_column('notas_fiscais', 'observacao',
               existing_type=sa.TEXT(),
               comment='Observacoes livres sobre a NF',
               existing_comment='Campo livre. Origem: coluna OBSERVAÇÃO.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'erro_calculo',
               existing_type=sa.TEXT(),
               comment='Descricao do erro caso status_calculo = ERRO. Usado para revisao operacional.',
               existing_comment='Descrição do erro (status_calculo = ERRO).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'status_calculo',
               existing_type=postgresql.ENUM('pendente', 'calculado', 'erro', 'ignorada', 'sem_tabela', 'sem_transportadora', name='statuscalculonf'),
               comment='Status atual do calculo de frete desta NF',
               existing_comment='Status do cálculo de frete (Seção 6.7).',
               existing_nullable=False)
    op.alter_column('notas_fiscais', 'nf_valor',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               nullable=False,
               comment='Valor total da nota fiscal em R$.',
               existing_comment='Valor total da nota fiscal em R$ (informativo).')
    op.alter_column('notas_fiscais', 'data_emissao',
               existing_type=sa.DATE(),
               comment='Data de emissao da nota fiscal',
               existing_comment='Data de emissão da nota fiscal',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'chave_nfe',
               existing_type=sa.VARCHAR(length=44),
               comment='Chave de acesso da NF-e (44 digitos). Opcional — usado na auditoria com CT-e.',
               existing_comment='Chave de acesso da NF-e (44 dígitos). Usada na auditoria CT-e (Seção 8.2).',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'serie_nf',
               existing_type=sa.VARCHAR(length=10),
               comment='Serie da nota fiscal. Ex: 001, A, B.',
               existing_comment='Série da nota fiscal. Ex: 001, A, B.',
               existing_nullable=True)
    op.alter_column('notas_fiscais', 'numero_nf',
               existing_type=sa.VARCHAR(length=50),
               comment='Numero da nota fiscal. Unico dentro do embarque.',
               existing_comment='Número do documento/NF. Origem: coluna DOCUMENTO da planilha.',
               existing_nullable=False)
    op.drop_column('notas_fiscais', 'centro_custo')
    op.drop_column('notas_fiscais', 'peso_kg_usado')
    op.drop_column('notas_fiscais', 'valor_kg_adicional_usado')
    op.drop_column('notas_fiscais', 'preco_ate_30kg_usado')
    op.drop_column('notas_fiscais', 'prazo_dias')
    op.drop_column('notas_fiscais', 'valor_calculado')
    op.drop_column('notas_fiscais', 'transportadora_id')
    op.drop_column('notas_fiscais', 'peso_total_kg')
    op.drop_column('notas_fiscais', 'qtd_cx')
    op.drop_column('notas_fiscais', 'cod_produto')
    op.drop_column('notas_fiscais', 'cidade_remetente_raw')
    op.drop_column('notas_fiscais', 'uf_remetente')
    op.drop_column('notas_fiscais', 'cidade_remetente')
    op.drop_column('notas_fiscais', 'cnpj_remetente')
    op.drop_column('notas_fiscais', 'cliente_remetente')
    op.drop_column('notas_fiscais', 'cod_remetente')
    op.drop_column('notas_fiscais', 'cidade_destino_raw')
    op.drop_column('notas_fiscais', 'uf_destino')
    op.drop_column('notas_fiscais', 'cidade_destino')
    op.drop_column('notas_fiscais', 'cnpj_destino')
    op.drop_column('notas_fiscais', 'cliente_destino')
    op.drop_column('notas_fiscais', 'cod_cliente')
    op.alter_column('faixas_frete', 'valor_minimo_faixa',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Valor mínimo cobrado nesta faixa em reais. Se frete calculado < valor_minimo_faixa, cobra valor_minimo_faixa.',
               existing_comment='Valor mínimo cobrado nesta faixa em reais. No MVP, usado apenas na faixa 1 (0 → 30 kg) como preço fixo para fretes até 30 kg.',
               existing_nullable=True)
    op.alter_column('faixas_frete', 'valor_kg',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Valor por kg nesta faixa em reais. Usado tanto em por_faixa quanto em progressivo.',
               existing_comment='Valor por kg nesta faixa em reais. No MVP, usado apenas na faixa 2 (30 kg → ∞) como adicional por kg excedente.',
               existing_nullable=False)
    op.drop_index('ix_empresas_tipo_codigo_terceiro', table_name='empresas')
    op.drop_index(op.f('ix_empresas_tipo'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_codigo_terceiro'), table_name='empresas')
    op.alter_column('empresas', 'trial',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True = empresa em período de trial',
               existing_comment='True = tenant em período de trial (NULL para terceiros)')
    op.alter_column('empresas', 'plano',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Plano contratado: basico | profissional | enterprise',
               existing_comment='Plano do tenant: basico | profissional | enterprise (NULL para terceiros)')
    op.alter_column('empresas', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               comment='Identificador amigável único para URL. Ex: acme-logistica',
               existing_comment='Identificador URL do tenant. Ex: acme-logistica (NULL para terceiros)')
    op.alter_column('empresas', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               comment='Telefone de contato da empresa',
               existing_comment='Telefone de contato',
               existing_nullable=True)
    op.alter_column('empresas', 'email_contato',
               existing_type=sa.VARCHAR(length=255),
               comment='E-mail principal de contato da empresa',
               existing_comment='E-mail principal de contato',
               existing_nullable=True)
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               comment='CNPJ formatado: 00.000.000/0000-00',
               existing_comment='CNPJ formatado: 00.000.000/0000-00 (único global)',
               existing_nullable=False)
    op.alter_column('empresas', 'nome_fantasia',
               existing_type=sa.VARCHAR(length=200),
               comment='Nome fantasia da empresa cliente',
               existing_comment='Nome fantasia',
               existing_nullable=True)
    op.alter_column('empresas', 'razao_social',
               existing_type=sa.VARCHAR(length=200),
               comment='Razão social da empresa cliente',
               existing_comment='Razão social (tenant ou terceiro)',
               existing_nullable=False)
    op.drop_column('empresas', 'tipo_pessoa')
    op.drop_column('empresas', 'codigo_terceiro')
    op.drop_column('empresas', 'tipo')
    # ### end Alembic commands ###
