"""remove_cubagem_and_frete_fields_from_notas_fiscais

Revision ID: f27d4de3245e
Revises: e5a1c9f4b7d2
Create Date: 2026-07-06 19:50:21.924672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27d4de3245e'
down_revision: Union[str, None] = 'e5a1c9f4b7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notas_fiscais', 'peso_real_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. É a métrica única de peso para cálculo de frete — o projeto NÃO utiliza cubagem.',
               existing_comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha.',
               existing_nullable=False)
    op.drop_column('notas_fiscais', 'comprimento_cm')
    op.drop_column('notas_fiscais', 'altura_cm')
    op.drop_column('notas_fiscais', 'peso_cubado_kg')
    op.drop_column('notas_fiscais', 'peso_frete_kg')
    op.drop_column('notas_fiscais', 'largura_cm')
    op.alter_column('transportadoras', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='Se False, transportadora não pode ser selecionada em novos embarques',
               existing_comment='False = registro inativo (soft delete)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transportadoras', 'ativo',
               existing_type=sa.BOOLEAN(),
               comment='False = registro inativo (soft delete)',
               existing_comment='Se False, transportadora não pode ser selecionada em novos embarques',
               existing_nullable=False)
    op.add_column('notas_fiscais', sa.Column('largura_cm', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True, comment='Largura unitária do volume em cm'))
    op.add_column('notas_fiscais', sa.Column('peso_frete_kg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True, comment='Peso usado no cálculo do frete. = max(peso_real_kg, peso_cubado_kg). Preenchido pelo engine de cálculo.'))
    op.add_column('notas_fiscais', sa.Column('peso_cubado_kg', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True, comment='Peso cubado calculado em kg. = (C × L × A em cm³) / fator_cubagem. NULL se dimensões não informadas.'))
    op.add_column('notas_fiscais', sa.Column('altura_cm', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True, comment='Altura unitária do volume em cm'))
    op.add_column('notas_fiscais', sa.Column('comprimento_cm', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True, comment='Comprimento unitário do volume em cm'))
    op.alter_column('notas_fiscais', 'peso_real_kg',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha.',
               existing_comment='Peso real da mercadoria em kg, conforme informado na NF ou planilha. É a métrica única de peso para cálculo de frete — o projeto NÃO utiliza cubagem.',
               existing_nullable=False)
    # ### end Alembic commands ###
